### PR TITLE
added default constructor in all api-related objects to fix a parse error

### PR DESCRIPTION
**Pull request by MelvinV**
api's didn't work because the objects cannot be parsed without a default constructor...

### CODE REVIEW

**Comment by javaxplorer** [comment]
In this assignment the stub is well... just a stub (https://en.wikipedia.org/wiki/Test_stub). So if you're reusing objects from the stub in your own application by adding them to the classpath, you're actually making your application depedent on a teststub instead of a real application.

A service can expose its contract in various ways. In the best case there is a driver provided to talk to the thing that is maintained by the same company that writes the software. If there's no driver then your best hope is to get an XSD (or JSD) that you can use to generate the model from - or perhaps even a WADL. Then there are of course api's that don't give you anything then just the endpoints with a bunch of json/xml output. 

So then you may wonder; where are the drivers? They are missing (intensionally) to trigger you on choosing your own solution there.

Given the above, I'll close this pullrequest :)

**Comment by pvdissel** [comment]
@MelvinV but ofcourse a big :+1: on creating the PR with this suggestion

**Comment by MelvinV** [comment]
@cjhkramer , @pvdissel ,

i don't think you guys quite get it.
the 3 microservices supplied should work right...?
we're supposed to consume them in our own microservice (pricenotificationservice)

the issue is that the services supplied do NOT work because the default constructor is not present.
for example take the emailservice... when i try to send an email by calling the POST functionality, the emailservice can not parse the Email to an object since the default constructor is not present.

would have been a good idea to test whether supplied code works before distributing it to us students. 👎

**Comment by pvdissel** [comment]
@MelvinV hmm... now I understand your issue. Tried it and it's reproducable...
But this is only an issue for the Email class, as that's the only one that's pushed to an API.
I got the fix, but as you did the PR from the master (which is discouraged because now I cannot append to your PR, always do a PR from a branch which is specificly for the PR for easier collaboration, something for next-time :)).

So I will close this issue, and apply the fix in the Email class

**Comment by pvdissel** [comment]
And @MelvinV, of course, again thanks for the PR, and sorry for the inconvenience

**Pull request closed without merging**
